name: Maven CI

on:
  push:
    branches:
      - master
      - "feature/**"
    paths:
      - "**.cpp"
      - "**.h"
      - "**.java"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [13]

    env:
      WEBRTC_CACHE_BRANCH: 4844
      WEBRTC_CHECKOUT_FOLDER: webrtc
      WEBRTC_INSTALL_FOLDER: webrtc/build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Linux audio system
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio libpulse-dev libasound2-dev libudev-dev libv4l-dev
          # Required for testing
          pulseaudio --start

      - name: Set up WebRTC cache
        uses: actions/cache@v1
        with:
          path: ~/${{ env.WEBRTC_INSTALL_FOLDER }}
          key: webrtc-${{ env.WEBRTC_CACHE_BRANCH }}-${{ runner.os }}-${{ hashFiles('webrtc-jni/pom.xml') }}
          restore-keys: webrtc-${{ env.WEBRTC_CACHE_BRANCH }}-${{ runner.os }}-

      - name: Set up Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          settings-path: ${{ github.workspace }}/.github/workflows

      - name: Install mvn package
        run: mvn install

      - name: Upload m2 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: m2
          path: ~/.m2/repository/dev/onvoid/webrtc/**
